== Link to browser

https://toledorafael.github.io/neo4j-browser/

== Login

* URL: `bolt://7700b2ee.databases.neo4j.io:7687`
* Username: `neo4j`
* Password: `0stYahwzlsJY3mSsJqxryOBixz1stUddecbKbiy0N2I`

== Query 1
[source]
----
MATCH p=(n{id:"f2"})-[r:alterBehaviour]->(m{id:"f1"}) 
MATCH q=(n)-[t:write]->()-[s:varWrite]->()-[u:varInfFunc]->(m)
return p,q
----

=== Task 1.1
Which facts are present in a variant with the following configuration?

* CommandInterpreter /\ !ControllerSystem

=== Task 1.2
What would happen if the feature ControllerSystem is enabled in the previous configuration?

* CommandInterpreter /\ ControllerSystem

=== Task 1.3
How many of the following configurations include the alterBehaviour link?

* FC1: CommandInterpreter /\ !ControllerSystem
* FC2: CommandInterpreter /\ ControllerSystem
* FC3: CommandInterpreter /\ ControllerSystem /\ !FunctionalSafetyUnit /\ LinearInterpolatedMotion
* FC4: CommandInterpreter /\ ControllerSystem /\ FunctionalSafetyUnit /\ LinearInterpolatedMotion

== Query 2
[source]
----
MATCH p=(n)-[r:alterBehaviour]->(m) 
MATCH q=(n)-[t:write]->()-[s:varWrite*3]->()-[u:varInfFunc]->(m)
return p,q
----

=== Task 2.1
Which facts are present in a variant with the following configuration?

* CoordinateSystem /\ !OpticalEncoder /\ !SafetyMonitoredStop /\ ShockDetectionFunction

=== Task 2.2
What would happen if the feature CoordinateSystem was disabled and feature SafetyMonitoredStop was enabled?

* !CoordinateSystem /\ !OpticalEncoder /\ SafetyMonitoredStop /\ ShockDetectionFunction

=== Task 2.3
How many of the following configurations include all the alterBehaviour links?

* FC1: CoordinateSystem /\ !OpticalEncoder /\ !SafetyMonitoredStop /\ !ShockDetectionFunction
* FC2: !OpticalEncoder /\ !CoordinateSystem /\ SafetyMonitoredStop /\ ShockDetectionFunction
* FC3: CoordinateSystem /\ SafetyMonitoredStop /\ ShockDetectionFunction
* FC4: OpticalEncoder /\ SafetyMonitoredStop /\ ShockDetectionFunction
