== Link to browser

https://toledorafael.github.io/neo4j-browser/

== Login

* URL: `bolt://7700b2ee.databases.neo4j.io:7687`
* Username: `neo4j`
* Password: `0stYahwzlsJY3mSsJqxryOBixz1stUddecbKbiy0N2I`

== Query 1
[source]
----
MATCH p=(n)-[r:varWrite|write|read]->(m) WHERE EXISTS(r.condition) AND r.condition <> "true" RETURN p
----

T1 - How many varWrites in this graph may happen in a directed weighted graph (kDirected /\ !kUndirected /\ kWeighted)?

T2 - How many links are introduced when we enable the feature kDFS in a variant with original configuration equal to kUndirected /\ kWeighted /\ !kDirected /\ !kDFS /\ !kBFS?

== Query 2
[source]
----
MATCH p=()-[r:call]->()-[q:write]->()-[:varWrite]->() where r.condition <> 'true' and q.condition <> 'true' return p
----

Considering the variants:

V1: kUndirected /\ kWeighted /\ kDFS /\ !kBFS /\ !kDirected

V2: kDirected /\ kWeighted /\ kBFS /\ !kDFS /\ !kUndirected

V3: kUndirected /\ !kWeighted /\ kBFS /\ !kDFS /\ !kDirected

V4: kUndirected /\ kWeighted /\ kBFS /\ !kDFS /\ !kDirected

T3 - Which variant includes all of the call-write-varWrite paths?
T4 - Which variant includes only one of the call-write-varWrite paths?
